server:
  port: 8081

spring:
  application:
    name: micro2
  data:
    mongodb:
      uri: mongodb+srv://administrador:Sencilla2016@cluster0.ynyfcec.mongodb.net/meseroapp
      database: meseroapp

cloudinary:
  cloud_name: jiliar-antonio-silgado-cardona
  api_key : 683867121112246
  api_secret : FepAFQe9AEaShWNhiEOufUQU6sI
  secure : true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
